name: PangLib.DAT (Build)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: "PangLib.DAT/**/*.*"
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          cache: true
      - name: Install dependencies
        run: cd PangLib.DAT && dotnet restore
      - name: Build project
        run: cd PangLib.DAT && dotnet build